title:              Code Pretty
description:        Too Pretty to Code Ugly
author:             Start Bootstrap
baseurl:            "/"
url:                "codepretty.tech"

# Social Profiles
instagram_username:  jocee.holladay
maincolor: "F2CBCB"
secondarycolor: "9c0045"

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-redirect-from
  
whitelist:
  - jekyll-redirect-from
collections:
  books:
    output: true
    permalink: /:collection/:title
  pages:
    output: true
    permalink: /:collection/:title
  code_princess:
    output: true
    permalink: /:collection/:title
  products:
    output: true
    permalink: /:collection/:title

contact_url: https://jadenholladay.herokuapp.com/jocee

maincolor: '#F2CBCB'
secondarycolor: '#F2CBCB'
compliment: '#9c0045'